#ifndef _EI_CLASSIFIER_MODEL_H_
#define _EI_CLASSIFIER_MODEL_H_

// Include the Edge Impulse SDK C++ headers (even if using C functions)
// Adjust path based on how you integrate the library
#include "edge-impulse-sdk/classifier/ei_classifier_types.h"

// --- Model Parameters (Generated by Edge Impulse) ---
// These values would be specific to your trained model.
#define EI_CLASSIFIER_DSP_INPUT_FRAME_SIZE     (FFT_SIZE / 2) // Example: Input is 128 PSD values
#define EI_CLASSIFIER_RAW_SAMPLE_COUNT         FFT_SIZE       // Example: Corresponds to 256 time samples
#define EI_CLASSIFIER_RAW_SAMPLES_PER_FRAME    1              // Usually 1 unless using sample sequences
#define EI_CLASSIFIER_DSP_BLOCK_COUNT          1
#define EI_CLASSIFIER_INPUT_WIDTH              (EI_CLASSIFIER_DSP_INPUT_FRAME_SIZE) // Width of feature vector
#define EI_CLASSIFIER_INPUT_HEIGHT             1
#define EI_CLASSIFIER_INTERVAL_MS              ( (float)EI_CLASSIFIER_RAW_SAMPLE_COUNT * 1000.0f / (float)SAMPLE_RATE_HZ ) // Window length in ms
#define EI_CLASSIFIER_LABEL_COUNT              2 // Example: "Normal", "BearingFail"
#define EI_CLASSIFIER_HAS_ANOMALY              0 // 1 if anomaly detection is used
#define EI_CLASSIFIER_FREQUENCY                SAMPLE_RATE_HZ

// Classifier object declaration
extern ei_classifier_t classifier;

// --- Function Prototypes (Generated by Edge Impulse) ---

/**
 * @brief      Initialize the classifier context object.
 *
 * @param      ctx   The context object. Needs to be allocated. Check library docs.
 *
 * @return     The ei impulse error.
 */
EI_IMPULSE_ERROR ei_classifier_init(ei_classifier_t *ctx);

/**
 * @brief      Get the classifier results for a signal object
 *
 * @param      ctx        Pointer to the classifier context object.
 * @param[in]  signal     Pointer to the signal object. Raw data or features. Check library docs.
 * @param[out] result     Pointer to struct that will receive the results
 * @param[in]  debug_nn   Whether to print debug information from the NN classifier.
 *
 * @return     The ei impulse error.
 */
EI_IMPULSE_ERROR ei_run_classifier(
    ei_classifier_t *ctx,
    signal_t *signal,
    ei_impulse_result_t *result,
    bool debug_nn = false);

/**
 * Run the impulse, if you provide an Edge Impulse sensor object this will automatically fill the buffer.
 * Or you can manually fill the buffer using `classifier_ctx->buf_idx = 0;` and then calling
 * `classifier_ctx->model_input->set_input(item, ...)`.
 *
 * @param ctx Pointer to the classifier context object
 * @param get_data_fn Function pointer to sensor acquisition function. Can be NULL if buffer filled manually.
 * @param result Pointer to store the classification result
 * @param debug Enable debug messages
 * @return EI_IMPULSE_ERROR
 */
EI_IMPULSE_ERROR run_nn_inference(
    ei_classifier_t *ctx,
    std::function<int(float*, size_t)> get_data_fn,
    ei_impulse_result_t *result,
    bool debug = false
);


// NOTE: The exact function signatures and required includes depend on the
// specific Edge Impulse library version and deployment options selected.
// This header (and the corresponding .c file) MUST be generated from your
// Edge Impulse Studio project after training.

#endif // _EI_CLASSIFIER_MODEL_H_